dskpayment_configuration_form:
  path: /dskpayment/configuration_form
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\DskPayment\Controller\DskPaymentConfigurationController::index'
